export const CustomPhysicalCardTypesList = [
  {
    "PhysicalCardTypeId":2,
    "CardTypeName":"Ribbon Card",
    "ImageUrl":"/images/RibbonCard.png",
    "DenominationDescription":"3.375 * 1.25",
    "Denomation":null,
    "Quantity":null,
    "Type": null
  },
  {
    "PhysicalCardTypeId":3,
    "CardTypeName":"Holiday Card",
    "ImageUrl":"/images/HolidayCard.png",
    "DenominationDescription":"3.375 * 0.75",
    "Denomation":null,
    "Quantity":null,
    "Type": null
  },
  {
    "PhysicalCardTypeId":7,
    "CardTypeName":"Fully Custom Card",
    "ImageUrl":"/images/FullyCustomCard.png",
    "DenominationDescription":"3.375 * 2.15 (plus 1/8\" bleed)",
    "Denomation":null,
    "Quantity":null,
    "Type": null
  }
]

export const OccasionsList = [
  { value: 'Anniversary', label: 'Anniversary' },
  { value: 'Award', label: 'Award' },
  { value: 'Baby', label: 'Baby' },
  { value: 'BabyBirthday', label: 'Baby Birthday' },
  { value: 'Birthday', label: 'Birthday' },
  { value: 'Celebration', label: 'Celebration' },
  { value: 'CharityChoiceGiftCard', label: 'CharityChoice Gift Card' },
  { value: 'CorporateLogo', label: 'Corporate Logo' },
  { value: 'CustomImage', label: 'Custom Image' },
  { value: 'CustomizableGraphic', label: 'Customizable Graphic' },
  { value: 'Environment', label: 'Environment - Show Your Green' },
  { value: 'Ethnic', label: 'Ethnic' },
  { value: 'FathersDay', label: 'Fathers Day' },
  { value: 'Friendship', label: 'Friendship' },
  { value: 'Get Well', label: 'GetWell' },
  { value: 'GiftBoxMotif', label: 'Gift Box Motif' },
  { value: 'Friendship', label: 'Friendship' },
  { value: 'GivingGiftCard', label: 'GivingGift Card: any occasion' },
  { value: 'Graduation', label: 'Graduation' },
  { value: 'Holiday', label: 'Holiday' },
  { value: 'Housewarming', label: 'Housewarming' },
  { value: 'Military', label: 'Military' },
  { value: 'MothersDay', label: 'Mothers Day' },
  { value: 'NewYear', label: 'New Year' },
  { value: 'Romance', label: 'Romance' },
  { value: 'Housewarming', label: 'Housewarming' },
  { value: 'SeasonGreetings', label: 'Season\'s Greetings' },
  { value: 'StockingStuffers', label: 'Stocking Stuffers' },
  { value: 'Superbowl', label: 'Superbowl' },
  { value: 'Sympathy', label: 'Sympathy' },
  { value: 'ThankYou', label: 'Thank You' },
  { value: 'ValentinesDay', label: 'Valentines Day' },
  { value: 'Wedding', label: 'Wedding' },
  { value: 'OtherOccasion', label: 'Other Occasion' }
]

export const LayoutList = [
  { value: 'CardSize', label: 'One Sided - Card Size' },
  { value: 'FullPage', label: 'One sided - Full Page' }
]

export const CardDesignList = [
  {
    id: 1,
    ImageUrl: "/images/Birthdaycard.jpg"
  },
  {
    id: 2,
    ImageUrl: "/images/CharityChoiceSeasonPrepaidCard.gif",
  },
  {
    id: 3,
    ImageUrl: "/images/CharityChoicePrepaidCard.gif"
  },
  {
    id: 4,
    ImageUrl: "/images/Weddingcard.jpg",
  },
  {
    id: 5,
    ImageUrl: "/images/CharityChoicePrepaidCard.gif",
  },
  {
    id: 6,
    ImageUrl: "/images/StockingStufferCard.png"
  },
  {
    id: 7,
    ImageUrl: "/images/Birthdaycard.jpg",
  }
]

export const CardBackgroundSchemesList = [
  {
    label: 'Elegant Gray',
    value: 'rgb(115, 114, 109)'
  },
  {
    label: 'Gold',
    value: 'rgb(255, 211, 86)'
  },
  {
    label: 'Green',
    value: 'rgb(0, 117, 21)'
  },
  {
    label: 'Holiday Red',
    value: 'rgb(192, 24, 13)'
  },
  {
    label: 'Torquoise',
    value: 'rgb(80, 155, 184)'
  }
]

export const DeliveryMethodList = [
  { value: 'Email', label: 'Email' },
  { value: 'Message', label: 'Text Message' },
  { value: 'Share', label: 'Share via messaging' }
];

export const AmountList = [
  { value: 5, label: '$5.00' },
  { value: 10, label: '$10.00' },
  { value: 25, label: '$25.00' },
  { value: 50, label: '$50.00' },
  { value: 100, label: '$100.00' },
  { value: 500, label: '$500.00' }
];

export const DonationAmountList = [
  { value: 2, label: '$2.00' },
  { value: 3, label: '$3.00' },
  { value: 5, label: '$5.00' },
  { value: 10, label: '$10.00' },
  { value: 15, label: '$15.00' },
  { value: 18, label: '$18.00' },
  { value: 20, label: '$20.00' },
  { value: 25, label: '$25.00' },
  { value: 35, label: '$35.00' },
  { value: 36, label: '$36.00' },
  { value: 50, label: '$50.00' },
  { value: 75, label: '$75.00' },
  { value: 100, label: '$100.00' },
  { value: 150, label: '$150.00' },
  { value: 180, label: '$180.00' },
  { value: 200, label: '$200.00' },
  { value: 250, label: '$250.00' },
  { value: 500, label: '$500.00' },
  { value: 750, label: '$750.00' },
  { value: 1000, label: '$1000.00' },
  { value: 1800, label: '$1800.00' },
  { value: 5000, label: '$5000.00' }
];

export const CountryList = [
  { value: 'AL', label: 'Alabama' },
  { value: 'AK', label: 'Alaska' },
  { value: 'AB', label: 'Alberta' },
  { value: 'AS', label: 'American Samoa' },
  { value: 'AZ', label: 'Arizona' },
  { value: 'AR', label: 'Arkansas' },
  { value: 'AA', label: 'Armed Forces Americas' },
  { value: 'AE', label: 'Armed Forces Canada/Europe/Middle East/Africa' },
  { value: 'AP', label: 'Armed Forces Pacific' },
  { value: 'BC', label: 'British Columbia' },
  { value: 'CA', label: 'California' },
  { value: 'CO', label: 'Colorado' },
  { value: 'CT', label: 'Connecticut' },
  { value: 'DE', label: 'Delaware' },
  { value: 'DC', label: 'District of Columbia' },
  { value: 'FL', label: 'Florida' },
  { value: 'GA', label: 'Georgia' },
  { value: 'GU', label: 'Guam' },
  { value: 'HI', label: 'Hawaii' },
  { value: 'ID', label: 'Idaho' },
  { value: 'IL', label: 'Illinois' },
  { value: 'IN', label: 'Indiana' },
  { value: 'IA', label: 'Iowa' },
  { value: 'KS', label: 'Kansas' },
  { value: 'KY', label: 'Kentucky' },
  { value: 'LA', label: 'Louisiana' },
  { value: 'ME', label: 'Maine' },
  { value: 'MB', label: 'Manitoba' },
  { value: 'MH', label: 'Marshall Islands' },
  { value: 'MD', label: 'Maryland' },
  { value: 'MA', label: 'Massachusetts' },
  { value: 'MI', label: 'Michigan' },
  { value: 'FM', label: 'Micronesia' },
  { value: 'MN', label: 'Minnesota' },
  { value: 'UM', label: 'Minor Outlying Islands' },
  { value: 'MS', label: 'Mississippi' },
  { value: 'MO', label: 'Missouri' },
  { value: 'MT', label: 'Montana' },
  { value: 'NE', label: 'Nebraska' },
  { value: 'NV', label: 'Nevada' },
  { value: 'NB', label: 'New Brunswick' },
  { value: 'NH', label: 'New Hampshire' },
  { value: 'NJ', label: 'New Jersey' },
  { value: 'NM', label: 'New Mexico' },
  { value: 'NY', label: 'New York' },
  { value: 'NL', label: 'Newfoundland and Labrador' },
  { value: 'NC', label: 'North Carolina' },
  { value: 'ND', label: 'North Dakota' },
  { value: 'MP', label: 'Northern Mariana Islands' },
  { value: 'NT', label: 'Northwest Territories' },
  { value: 'NS', label: 'Nova Scotia' },
  { value: 'NU', label: 'Nunavut' },
  { value: 'OH', label: 'Ohio' },
  { value: 'OK', label: 'Oklahoma' },
  { value: 'ON', label: 'Ontario' },
  { value: 'OR', label: 'Oregon' },
  { value: 'PW', label: 'Palau' },
  { value: 'PA', label: 'Pennsylvania' },
  { value: 'PE', label: 'Prince Edward Island' },
  { value: 'PR', label: 'Puerto Rico' },
  { value: 'QC', label: 'Quebec' },
  { value: 'RI', label: 'Rhode Island' },
  { value: 'SK', label: 'Saskatchewan' },
  { value: 'SC', label: 'South Carolina' },
  { value: 'SD', label: 'South Dakota' },
  { value: 'TN', label: 'Tennessee' },
  { value: 'TX', label: 'Texas' },
  { value: 'UT', label: 'Utah' },
  { value: 'VT', label: 'Vermont' },
  { value: 'VI', label: 'Virgin Islands' },
  { value: 'VA', label: 'Virginia' },
  { value: 'WA', label: 'Washington' },
  { value: 'WV', label: 'West Virginia' },
  { value: 'WI', label: 'Wisconsin' },
  { value: 'WY', label: 'Wyoming' },
  { value: 'YT', label: 'Yukon' }
];

export const MerchatList = [
  { value: '1', label: '1 800 Flowers.com'},
  { value: '2', label: '1800PetSupplies.com'},
  { value: '3', label: 'Abercrombie'},
  { value: '4', label: 'Adidas'},
  { value: '5', label: 'Aerie'},
  { value: '6', label: 'Aeropostale'},
  { value: '7', label: 'Allen Edmonds'},
  { value: '8', label: 'AMC Theatres'},
  { value: '9', label: 'American Airlines'},
  { value: '10', label: 'American Eagle Outfitters'},
  { value: '', label: 'Anthropologie'},
  { value: '', label: 'Applebee\'s'},
  { value: '', label: 'Athleta'},
  { value: '', label: 'Avenue'},
  { value: '', label: 'Baby Gap'},
  { value: '', label: 'Bahama Breeze'},
  { value: '', label: 'Ballard Designs'},
  { value: '', label: 'Banana Republic'},
  { value: '', label: 'Barnes &amp; Noble'},
  { value: '', label: 'Bass Pro Shops'},
  { value: '', label: 'Bath &amp; Body Works'},
  { value: '', label: 'Bed &amp; Breakfast'},
  { value: '', label: 'Bed Bath &amp; Beyond'},
  { value: '', label: 'Belk'},
  { value: '', label: 'Best Buy'},
  { value: '', label: 'Best Western'},
  { value: '', label: 'BJ\'s Restaurant'},
  { value: '', label: 'Black Angus'},
  { value: '', label: 'Bloomingdale\'s'},
  { value: '', label: 'Bob Evans'},
  { value: '', label: 'Boscov\'s'},
  { value: '', label: 'Boston Market'},
  { value: '', label: 'Bravo! Cucina Italiano'},
  { value: '', label: 'Brinker Restaurants'},
  { value: '', label: 'Brooks Brothers'},
  { value: '', label: 'Buca di Beppo'},
  { value: '', label: 'Buckle'},
  { value: '', label: 'Buffalo Wild Wings'},
  { value: '', label: 'Build A Bear'},
  { value: '', label: 'Burberry'},
  { value: '', label: 'Burlington Coat Factory'},
  { value: '', label: 'Cabela\'s'},
  { value: '', label: 'Capital Grille'},
  { value: '', label: 'Carmike Cinemas'},
  { value: '', label: 'Carnival Cruises'},
  { value: '', label: 'Carrows'},
  { value: '', label: 'Carters'},
  { value: '', label: 'Casual Male XL'},
  { value: '', label: 'Catherines'},
  { value: '', label: 'Champs Sports'},
  { value: '', label: 'Charming Charlie'},
  { value: '', label: 'Cheesecake Factory'},
  { value: '', label: 'Chevys Fresh Mex'},
  { value: '', label: 'Chico\'s'},
  { value: '', label: 'Chipotle'},
  { value: '', label: 'Christopher &amp; Banks'},
  { value: '', label: 'Cinemark'},
  { value: '', label: 'Claim Jumper'},
  { value: '', label: 'Coco\'s'},
  { value: '', label: 'Coffee Bean'},
  { value: '', label: 'Cold Stone Creamery'},
  { value: '', label: 'Cole Haan'},
  { value: '', label: 'Columbia Sportswear'},
  { value: '', label: 'Container Store'},
  { value: '', label: 'Converse'},
  { value: '', label: 'Crate &amp; Barrel'},
  { value: '', label: 'Crazy 8'},
  { value: '', label: 'Crutchfield'},
  { value: '', label: 'Culver\'s'},
  { value: '', label: 'CVS'},
  { value: '', label: 'CVS Select'},
  { value: '', label: 'DA Gift'},
  { value: '', label: 'Darden Restaurants'},
  { value: '', label: 'Destination Maternity'},
  { value: '', label: 'Dick\'s Sporting Goods (Not Merchandise Credit)'},
  { value: '', label: 'Dollar Shave Club eGift'},
  { value: '', label: 'Domino\'s Pizza'},
  { value: '', label: 'DSW'},
  { value: '', label: 'Dunkin\' Donuts'},
  { value: '', label: 'eBay'},
  { value: '', label: 'Eddie Bauer'},
  { value: '', label: 'Elephant Bar'},
  { value: '', label: 'Express'},
  { value: '', label: 'Fairmont Hotels'},
  { value: '', label: 'Famous Dave\'s'},
  { value: '', label: 'Famous Footwear'},
  { value: '', label: 'Fandango'},
  { value: '', label: 'Finish Line'},
  { value: '', label: 'Foot Locker'},
  { value: '', label: 'Forever 21'},
  { value: '', label: 'Fye'},
  { value: '', label: 'G By Guess'},
  { value: '', label: 'G.H. Bass &amp; Co.'},
  { value: '', label: 'GameStop'},
  { value: '', label: 'Gap'},
  { value: '', label: 'Gap Kids'},
  { value: '', label: 'Gap Options'},
  { value: '', label: 'Godiva'},
  { value: '', label: 'Golf Galaxy'},
  { value: '', label: 'Groupon'},
  { value: '', label: 'Guess'},
  { value: '', label: 'Guitar Center'},
  { value: '', label: 'Gyu Kaku'},
  { value: '', label: 'H&amp;M'},
  { value: '', label: 'Hallmark Gold Crown'},
  { value: '', label: 'Harry &amp; David'},
  { value: '', label: 'Hewlett Packard HP'},
  { value: '', label: 'Hibbett Sports'},
  { value: '', label: 'Hollister'},
  { value: '', label: 'Home Depot'},
  { value: '', label: 'HomeGoods'},
  { value: '', label: 'Hot Topic'},
  { value: '', label: 'Hotels.com'},
  { value: '', label: 'Hyatt'},
  { value: '', label: 'IHOP'},
  { value: '', label: 'Izod'},
  { value: '', label: 'J. Crew'},
  { value: '', label: 'JCPenney'},
  { value: '', label: 'Jet Blue'},
  { value: '', label: 'Jiffy Lube'},
  { value: '', label: 'Jo-Ann'},
  { value: '', label: 'Johnny Carino\'s Italian'},
  { value: '', label: 'JoS. A. Bank'},
  { value: '', label: 'Journeys'},
  { value: '', label: 'Justice'},
  { value: '', label: 'Kate Spade'},
  { value: '', label: 'Kenneth Cole'},
  { value: '', label: 'Kids Foot Locker'},
  { value: '', label: 'Kirkland\'s'},
  { value: '', label: 'Kmart'},
  { value: '', label: 'Kohl\'s'},
  { value: '', label: 'L.L.Bean'},
  { value: '', label: 'Lady Foot Locker'},
  { value: '', label: 'Landmark Theatres'},
  { value: '', label: 'Landry\'s Restaurants'},
  { value: '', label: 'Lands\' End'},
  { value: '', label: 'Lane Bryant'},
  { value: '', label: 'Legal Sea Foods'},
  { value: '', label: 'LEGO Store'},
  { value: '', label: 'Lids'},
  { value: '', label: 'Logan\'s Roadhouse'},
  { value: '', label: 'LongHorn Steakhouse'},
  { value: '', label: 'Lord &amp; Taylor'},
  { value: '', label: 'Lord &amp; Taylor Online Only'},
  { value: '', label: 'Lowe\'s'},
  { value: '', label: 'Lucilles BBQ'},
  { value: '', label: 'Lucky Brand Jeans'},
  { value: '', label: 'Lululemon'},
  { value: '', label: 'Macaroni Grill'},
  { value: '', label: 'Madewell'},
  { value: '', label: 'Magazines.com'},
  { value: '', label: 'Maggiano\'s'},
  { value: '', label: 'Marriott'},
  { value: '', label: 'Marshalls'},
  { value: '', label: 'McCormick &amp; Schmick\'s'},
  { value: '', label: 'Men\'s Wearhouse'},
  { value: '', label: 'Michael Kors'},
  { value: '', label: 'Michaels'},
  { value: '', label: 'Mimis Cafe'},
  { value: '', label: 'MLB.com'},
  { value: '', label: 'Morton\'s The Steakhouse'},
  { value: '', label: 'Movietickets.com'},
  { value: '', label: 'Mr Porter'},
  { value: '', label: 'Nascar.com'},
  { value: '', label: 'NBA Store'},
  { value: '', label: 'Neiman Marcus'},
  { value: '', label: 'New York &amp; Company'},
  { value: '', label: 'New York &amp; Company Merchandise Credit'},
  { value: '', label: 'Newegg'},
  { value: '', label: 'Nflshop.com'},
  { value: '', label: 'Nhl.com'},
  { value: '', label: 'Nike'},
  { value: '', label: 'Nordstrom'},
  { value: '', label: 'North Face'},
  { value: '', label: 'Nutrisystem'},
  { value: '', label: 'Office Depot'},
  { value: '', label: 'Office Depot In Store Only'},
  { value: '', label: 'Office Max'},
  { value: '', label: 'Old Navy'},
  { value: '', label: 'Olive Garden'},
  { value: '', label: 'Omaha Steaks'},
  { value: '', label: 'On the Border'},
  { value: '', label: 'Orange Card'},
  { value: '', label: 'Oriental Trading'},
  { value: '', label: 'Origins'},
  { value: '', label: 'Orvis'},
  { value: '', label: 'OshKosh B\'Gosh'},
  { value: '', label: 'Overstock'},
  { value: '', label: 'P.F. Chang\'s'},
  { value: '', label: 'PacSun'},
  { value: '', label: 'Panera Bread'},
  { value: '', label: 'Panera Bread In Store Only (No PIN)'},
  { value: '', label: 'Papa Gino\'s'},
  { value: '', label: 'Papa Johns'},
  { value: '', label: 'Piccadilly'},
  { value: '', label: 'Piperlime'},
  { value: '', label: 'Pizza Hut'},
  { value: '', label: 'Polo Ralph Lauren'},
  { value: '', label: 'Potbelly'},
  { value: '', label: 'Pottery Barn'},
  { value: '', label: 'Pottery Barn Kids'},
  { value: '', label: 'Pottery Barn Teen'},
  { value: '', label: 'Puma'},
  { value: '', label: 'Qdoba'},
  { value: '', label: 'Ralph Lauren'},
  { value: '', label: 'Red Door Salon &amp; Spa'},
  { value: '', label: 'Red Lobster'},
  { value: '', label: 'Red Robin'},
  { value: '', label: 'Reebok'},
  { value: '', label: 'Regal Cinemas'},
  { value: '', label: 'Regal Entertainment'},
  { value: '', label: 'REI'},
  { value: '', label: 'Restaurants Unlimited'},
  { value: '', label: 'Ruby Tuesday'},
  { value: '', label: 'Ruth\'s Chris Steak House'},
  { value: '', label: 'Saks Fifth Avenue'},
  { value: '', label: 'Sams Club'},
  { value: '', label: 'Sears'},
  { value: '', label: 'Seasons 52'},
  { value: '', label: 'Sephora (Not Sephora at JCP)'},
  { value: '', label: 'Sharkys'},
  { value: '', label: 'Sheetz'},
  { value: '', label: 'Skechers'},
  { value: '', label: 'Smith &amp; Wollensky'},
  { value: '', label: 'Southwest Airlines'},
  { value: '', label: 'Spa &amp; Wellness Gift Card by Spa Week'},
  { value: '', label: 'Spafinder Wellness'},
  { value: '', label: 'Staples'},
  { value: '', label: 'Starbucks'},
  { value: '', label: 'Starbucks International'},
  { value: '', label: 'Steak \'n Shake'},
  { value: '', label: 'StubHub'},
  { value: '', label: 'Sunglass Hut'},
  { value: '', label: 'Supercuts'},
  { value: '', label: 'Sur La Table'},
  { value: '', label: 'Taco Bueno'},
  { value: '', label: 'Talbots'},
  { value: '', label: 'Target'},
  { value: '', label: 'Teavana'},
  { value: '', label: 'Texas Roadhouse'},
  { value: '', label: 'The Body Shop'},
  { value: '', label: 'The Children\'s Place'},
  { value: '', label: 'The Golf Warehouse'},
  { value: '', label: 'The Great Indoors'},
  { value: '', label: 'Ticketmaster'},
  { value: '', label: 'Tillys'},
  { value: '', label: 'Tim Hortons'},
  { value: '', label: 'Timberland'},
  { value: '', label: 'TJ Maxx'},
  { value: '', label: 'Tony Roma\'s'},
  { value: '', label: 'Torrid'},
  { value: '', label: 'Tory Burch'},
  { value: '', label: 'Ugg'},
  { value: '', label: 'Ulta'},
  { value: '', label: 'Under Armour'},
  { value: '', label: 'Urban Outfitters'},
  { value: '', label: 'US Airways'},
  { value: '', label: 'Vans'},
  { value: '', label: 'Vegas.com'},
  { value: '', label: 'Victorias Secret'},
  { value: '', label: 'Walmart'},
  { value: '', label: 'West Elm'},
  { value: '', label: 'Williams-Sonoma'},
  { value: '', label: 'Yankee Candle'},
  { value: '', label: 'Yard House'},
  { value: '', label: 'Z Gallerie'},
  { value: '', label: 'Zales'},
  { value: '', label: 'Zara'},
  { value: '', label: 'Zumiez'}
]
